version: "3"
services:
  mssql-server:
    container_name: mssql-server
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: Y
      # SET VALUE IN .env file (Use .env.test as reference)
      SA_PASSWORD: ${DB_PASS} 
    ports:
      - 1433:1433
    volumes: 
      - ./docker/mssql-server/backups:/var/opt/.backups
     #- ./docker/mssql-server/mssql:/var/opt/mssql
