version: "3"
services:
  mssql-server:
    container_name: mssql-server
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      SA_PASSWORD: "${DB_PASS}" # SET VALUE IN .env file (Use .env.test as reference)
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes: 
      - "./docker/mssql-server/.data:/var/opt/mssql"
     #  - "./docker/mssql-server/backups:/var/opt/.backups"